import eth from '../../assets/img/ic_eth_40.svg'
import usdc from '../../assets/img/ic_usdc_24.svg';
import btc from '../../assets/img/ic_btc.b_40.svg';
import bnb from '../../assets/img/ic_bnb_40.svg';

export const tokenList = [
  {
    name: 'USDC',
    desc: 'USD Coin',
    count: '$0.99',
    percent: '-1.13%',
    img: usdc,
  },
  {
    name: 'BTC',
    desc: 'Bitcoin',
    count: '$67826.92',
    percent: '+0.25%',
    img: btc,
  },
  {
    name: 'ETH',
    desc: 'Ethereum',
    count: '$3167.92',
    percent: '+0.25%',
    img: eth,
  },
  {
    name: 'USDC',
    desc: 'USDC',
    count: '$0.98',
    percent: '+0.25%',
    img: usdc,
  },
  {
    name: 'BNB',
    desc: 'Binance',
    count: '$593.35',
    percent: '+0.21%',
    img: bnb,
  },
  {
    name: 'BTC',
    desc: 'Bitcoin',
    count: '$67826.92',
    percent: '+0.25%',
    img: btc,
  },
  {
    name: 'ETH',
    desc: 'Ethereum',
    count: '$3167.92',
    percent: '+0.25%',
    img: eth,
  },
  {
    name: 'BTC',
    desc: 'Bitcoin',
    count: '$67826.92',
    percent: '+0.25%',
    img: btc,
  },
  {
    name: 'ETH',
    desc: 'Ethereum',
    count: '$3167.92',
    percent: '+0.25%',
    img: eth,
  },
  {
    name: 'BTC',
    desc: 'Bitcoin',
    count: '$67826.92',
    percent: '+0.25%',
    img: btc,
  },
  {
    name: 'ETH',
    desc: 'Ethereum',
    count: '$3167.92',
    percent: '+0.25%',
    img: eth,
  },
  {
    name: 'BNB',
    desc: 'Binance',
    count: '$593.35',
    percent: '+0.21%',
    img: bnb,
  },
  {
    name: 'BTC',
    desc: 'Bitcoin',
    count: '$67826.92',
    percent: '+0.25%',
    img: btc,
  },
  {
    name: 'ETH',
    desc: 'Ethereum',
    count: '$3167.92',
    percent: '+0.25%',
    img: eth,
  },
  {
    name: 'BTC',
    desc: 'Bitcoin',
    count: '$67826.92',
    percent: '+0.25%',
    img: btc,
  },
  {
    name: 'BNB',
    desc: 'Binance',
    count: '$593.35',
    percent: '+0.21%',
    img: bnb,
  },
  {
    name: 'ETH',
    desc: 'Ethereum',
    count: '$3167.92',
    percent: '+0.25%',
    img: eth,
  },
  {
    name: 'ETH',
    desc: 'Ethereum',
    count: '$3167.92',
    percent: '+0.25%',
    img: eth,
  },
  {
    name: 'BNB',
    desc: 'Binance',
    count: '$593.35',
    percent: '+0.21%',
    img: bnb,
  },
  {
    name: 'BTC',
    desc: 'Bitcoin',
    count: '$67826.92',
    percent: '+0.25%',
    img: btc,
  },
  {
    name: 'ETH',
    desc: 'Ethereum',
    count: '$3167.92',
    percent: '+0.25%',
    img: eth,
  },
  {
    name: 'BNB',
    desc: 'Binance',
    count: '$593.35',
    percent: '+0.21%',
    img: bnb,
  },
  {
    name: 'ETH',
    desc: 'Ethereum',
    count: '$3167.92',
    percent: '+0.25%',
    img: eth,
  },
  {
    name: 'BNB',
    desc: 'Binance',
    count: '$593.35',
    percent: '+0.21%',
    img: bnb,
  },
  {
    name: 'ETH',
    desc: 'Ethereum',
    count: '$3167.92',
    percent: '+0.25%',
    img: eth,
  },
  {
    name: 'BNB',
    desc: 'Binance',
    count: '$593.35',
    percent: '+0.21%',
    img: bnb,
  },
];
